#define MENU_TEXT_SIZE 3
#define MENU_TEXT_WIDTH 8
#define MENU_TEXT_HEIGHT 11

//STANDARD SMS MESSAGE LENGTH IS 160 CHARACTERS.
#define MESSAGE_LENGTH 160

#define PASTEL_GREEN 0xE77B
#define PASTEL_RED 0xFF3A
#define PASTEL_BLUE 0xDF5E
#define PASTEL_YELLOW 0xFF99
#define NES_RED 0xFB8D